# Generated by Django 2.2.5 on 2023-03-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('note_name', models.CharField(max_length=250)),
                ('note', models.FileField(upload_to='notes')),
                ('student', models.ManyToManyField(related_name='student_note', to='classroom.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_note', to='classroom.Teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
